### PR TITLE
CESNET migration to keycloak

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
Hi,

Could we test this on the development instance, please?

Best regards,
Sebastian

### CODE REVIEW

**Comment by micafer** [comment]
Hi @sebastian-luna-valero,

Changed in devel could you test it?

**Comment by micafer** [comment]
I tested and I get an error:
{"code":404,"message":"Could not find federated protocol oidc for Identity Provider: egi.eu.","title":"Not Found"}}!

**Comment by sebastian-luna-valero** [comment]
Thanks!

Replied we got from CESNET:

> The issue is how to add another openid for the same OS domain.

If you have any suggestions, please let us know.

**Comment by micafer** [comment]
Hi @sebastian-luna-valero,

I have just tested it, and now it seems to work.

**Comment by sebastian-luna-valero** [comment]
Indeed, it works on both the dev and the prod instances!

**Pull request closed without merging**
